before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
env:
env:
  global:
    - secure: RFlzPnMD/XcijrlAHePMzj4cCgIoCnZldFZFWGlg1dOKuZenGCF7CIhPK46DI2MYZQWxLCDtlUhz90L8EH2IPyp01jvCiZrVoofnl3u4B4B9X6/QpAKjnvvBG5/HN/i5zrgzKGizU7kP22GdXJZWWUWNuVO/fnfmHaeX3z3WRcN+CQrnIXiq0WVY47ecVfelUuSzsMqw/ld38I/Pj3rH9qHLlguF/iGqk/WPigtO7cj8ze17C3Q1Sl5TXEfUf8IIUWixnUh7oii1l0QVLlowpYc9M1Pvcb9jlLpi82u9SAmdJyXyUHAgf1QJYrfngoMJMWfyzBlZmkeOjLhLpDBgkRi5F2+SNAnK/KZwP8wjqc5mj/EJqFGpd1CmD3fCuC4hWJ3c/CSTSNF6kibERwVi/dX64FIytAx7r5NdLTuuinlevDIxkZIxkgNG6SmkpJ9uUqH9XLkpWt73purE/KeknRbVg7zgYff+vqlNrKJe8Ezguxs3iAfzZkn5U4lYu71kf3KRSCeO34hA61vbNyTqgxiMb6TeVur5T7YqHeMd/iA8LTEj8rEP9JsozeU9UEcN9c0GPQDKQNyYyWK5qC9XoVTjR9UAWod/C3m7jGB2lYnJuqhrZG86Zjp4oGg1NyuFzRQusAlCFUxq6d8oKX40tF7iXkNyhUXR7XzDTEdJYNU=
    - secure: HE3sxV20j619Bcru8LIf40F8WLtMMZ/BBVxsPFQEovj/z1GWxFa/aTrcrEpdDjnlAPMZHXe0Z1pAPXII6JtgUjYX1UsW+IUSdUVR41UTDgOMFCqILynUGsPbwGzGgijGD/vcKItdqZ2NO48VOa2iv6Vaq29LXLxJGbHm+E+kZ7pHYSCUrEQ9TUtD2SuWvbeW/fgLFE6sXNNahmEE8bJqSZEzEgqIT9ozLI9tP23o49V/RWg/pt4ChuqH7Qt3XiUGeYOOXbc3SxaVbPkVTg00asJB6NVADmJRjijf0saU4E0Ws7nFkfWGEnQ1BM8aSgnr/H/X7jPwJD8WBx2s0IQZUQDVpctrqDuiGFEMsjYUZxfeUPSXM8+EdB/tHQ2PFlRWTgK18jkhQkyJHsebfqVXAPmaNNRzI1boJ4yxj4C8UNayDyZSOifmje4x+LiegI7e5solzXYIHL7gK8w+wRu35sG6d6Osns37h04rfeWUcW7uGxTSxbAfkOlIkxBfqZhvSlp54EDyoIRxgrkqtxbHl7QvMJOhx1JVbUHFkWDTCOar8PTv6Q0awI5las5pqaaR1FWcySAEFVGwdyYwnMOxW02VOaTRfUAuAPPnm5mFumZMrXkN24piFYX7R08uWDkJ2z9Hdi4OFrhO30DhSZbUBGSSCX+aeiS5c9jDhz6AP9Y=
addons:
  sauce_connect: true
cache:
  directories:
  - node_modules
language: node_js
node_js:
- 0.12
script: |
  ./node_modules/.bin/shortcake test-ci
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: FxW7/9uXX6lydfhe0cbKRu5Aq82FEHSYqNEgUOmPJF5dWej07jtKdu0CuzDgEkMBXvRN3nouEdszl1lqdvb3s6e4UW+y6BhkdQxqEgN/Ch9Mk1LklFh1wk1yRJTHoZCHVk1QWqGzqBgMB0AHXNxe0RZrWqH1sAa4oFn2NIt2b79Wfrh25uPVnWIwl4t+CX/+vRvbBoGTXqhGJy8KQhzOystUsmuunVeOpg5gHSlHE2bc8a1QC9m51XxLcXfMV4rTuhfFHGVqPd4m1dDbhOVQRW1zMhoMkWl18V9qNOtOPT8q8NQwSBBHZ5/5d80BECGFIDF6fWcrqjGzzSTnxYmzRdCtBE7ni+y9f9+91WWNowJDckarW+91BpPi58RY6oSDvEOlD3ycMEGRuAFAXvW4cO0skWsUS0yA7OFv4K//g3Lbx0OEKZvy2zbmreLpmki9/8MkyP3geJNyv8SpxRFmBnF+Cx45amNgNN00Z8AVVJ1ad2hwV7YLJxlDej4PfP6cuyG1mwNO2gzk+n1FhjZgggKWIC8Winm0yEI6PrlEg3rJ5lcyQ3z/935Jy8seGE3mWRDyS/gNLa6vUhSRWNkDLVL9sYnLo/BLXZhtKDkQOSPAtb93eRlFoP4pvmj5BIryaUq7IoQB/QYTvvYHNEaSjWD9hyOBTWIDXTbR1SH/UNo=
